title: "Optimization-Aware Interpretability: Hands-On Methods for Explainable Automated Machine Learning Systems"
description: "IEEE WCCI 2026 Tutorial. Hybrid track for CEC / IJCNN / FUZZ."
theme: jekyll-theme-cayman
show_downloads: false
