title: Optimization-Aware Interpretability: Hands-On Methods for Explainable Automated Machine Learning Systems
description: Accepted tutorial at IEEE WCCI 2026.
theme: jekyll-theme-cayman
show_downloads: false
